### ISSUE TITLE
Can't get validation to work on form inside modal

### ISSUE THREAD

**Issue by oliverbj** [lepikhinb/momentum-modal#10] opened 2022-07-03 09:43 UTC
Hi!

I have a simple create form, where I am trying to get Form Validation to work:

![image](https://im4.ezgif.com/tmp/ezgif-4-d6a5e9a76b.gif)

As you can see in the above code it doesn't seem to validate the request when I click on "Create"

I have the below `Create.vue` form:

```vue
//Create.vue
<script setup>
import Modal from "@/Pages/Modal";
import CreatePipelineForm from "@/Pages/Pipeline/Partials/CreatePipelineForm";

</script>

<template>
    <Modal>
        <template #title> Create Pipeline </template>
        <CreatePipelineForm />
    </Modal>
</template>
```

Inside this create modal, I have a component called `CreatePipelineForm`:

```vue
//CreatePipelineForm.vue
<template>
    <studio-form-section @submitted="createPipeline">
        <template #form>
                <div class="col-span-6">
                    <text-input v-model="form.name" label="Name" :error="form.errors.name"></studio-input>
                </div>
        </template>
        <template #actions>
            <loading-button :loading="form.processing">
                Create
            </loading-button>
        </template>
    </studio-form-section>
</template>
<script setup>
import { useForm } from '@inertiajs/inertia-vue3';
import StudioFormSection from "@/Studio/FormSection";
import LoadingButton from "@/Studio/LoadingButton";

const form = useForm({
    name: '',
    output_type: 'text',
    description: '',
})

const createPipeline = () => {
    form.post(route('pipelines.store'), {
        errorBag: 'createPipeline',
        preserveScroll: true,
    })
}
</script>
```

Finally, below is the `store()` method in my controller:

```php
public function store(Request $request)
{
    \Auth::user()
        ->currentTeam->pipelines()
        ->create(
            $request->validate([
                "name" => "required|string|min:3|max:255",
            ])
        );

    return redirect()
        ->route("pipelines.index")
        ->with("success", "Pipeline created successfully.");
}
```

**Comment by lepikhinb** [comment] 2022-07-03 09:51
1. Can you also share the code of your base modal component?
2. Does this happen if you don’t use an error bag?
3. Can you inspect the query response and confirm that errors are present there?

Thanks

**Comment by oliverbj** [comment] 2022-07-03 19:14
> Can you also share the code of your base modal component?


Here is the code of the base modal component:

```vue
<script setup>
import { TransitionRoot, TransitionChild, Dialog, DialogPanel, DialogTitle } from "@headlessui/vue"
import { useModal } from "momentum-modal"

const { show, close, redirect } = useModal()
</script>

<template>
    <TransitionRoot appear as="template" :show="show" @after-leave="redirect">
        <Dialog as="div" class="relative z-10" @close="close">
            <TransitionChild
                @after-leave="redirect"
                as="template"
                enter="duration-300 ease-out"
                enter-from="opacity-0"
                enter-to="opacity-100"
                leave="duration-200 ease-in"
                leave-from="opacity-100"
                leave-to="opacity-0">
                <div class="fixed inset-0 bg-black/75 transition-opacity" />
            </TransitionChild>

            <div class="fixed inset-0 overflow-y-auto">
                <div class="flex min-h-full items-center justify-center p-4 text-center">
                    <TransitionChild
                        as="template"
                        enter="duration-300 ease-out"
                        enter-from="opacity-0 scale-95"
                        enter-to="opacity-100 scale-100"
                        leave="duration-200 ease-in"
                        leave-from="opacity-100 scale-100"
                        leave-to="opacity-0 scale-95">
                        <DialogPanel class="w-full max-w-xl transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all">
                            <DialogTitle as="h3" class="text-lg font-medium leading-6 text-gray-900">
                                <slot name="title" />
                            </DialogTitle>
                            <slot />
                        </DialogPanel>
                    </TransitionChild>
                </div>
            </div>
        </Dialog>
    </TransitionRoot>
</template>
```

> Does this happen if you don’t use an error bag?
Yes.

> Can you inspect the query response and confirm that errors are present there?

Checking the network tab in DevTools, there validation does happen:

```json
{
   "component":"Pipeline\/Index",
   "props":{
      //...
      "errorBags":{
         "default":{
            "name":[
               "The name field is required."
            ]
         }
      },
      "errors":{
         "name":"The name field is required."
      }
   }
   "url":"\/pipelines\/create",
   "version":"207fd484b7c2ceeff7800b8c8a11b3b6"
}
```

**Comment by lepikhinb** [comment] 2022-07-03 19:35
I couldn't reproduce the bug yet. Make sure the following syntax error is not the reason of the issue:
```vue
<text-input v-model="form.name" label="Name" :error="form.errors.name"></studio-input>
```

Check the closing tag **</studio-input>**.

**Comment by oliverbj** [comment] 2022-07-03 21:14
Sorry about the closing tag, that was a pasting error from my side. Unfortunately it didn't fix the issue.

If I remove the `<Modal>` component and just render the Inertia page normally, the validation works fine :(

Will try to debug some more..

**Comment by oliverbj** [comment] 2022-07-03 21:16
Weirdly enough, when submitting the form, it will redirect to the route provided in `baseRoute()` under the `create()` method and not the redirect route under the `store()` method.

**Comment by lepikhinb** [comment] 2022-07-03 21:18
Also make sure you’re using the latest version of the `npm` package. I published a release yesterday which may fixed the issue.

**Comment by cristophergv** [comment] 2022-07-04 03:58
> Hi!
> 
> I have a simple create form, where I am trying to get Form Validation to work:
> 
> ![image](https://camo.githubusercontent.com/bac75cc94a4f8916fe9d259c435d08fe0efa7d4a6e14feb5d2e5ed7fcde99037/68747470733a2f2f696d342e657a6769662e636f6d2f746d702f657a6769662d342d643661356539613736622e676966) [ ](https://camo.githubusercontent.com/bac75cc94a4f8916fe9d259c435d08fe0efa7d4a6e14feb5d2e5ed7fcde99037/68747470733a2f2f696d342e657a6769662e636f6d2f746d702f657a6769662d342d643661356539613736622e676966) ![image](https://camo.githubusercontent.com/bac75cc94a4f8916fe9d259c435d08fe0efa7d4a6e14feb5d2e5ed7fcde99037/68747470733a2f2f696d342e657a6769662e636f6d2f746d702f657a6769662d342d643661356539613736622e676966) [ ](https://camo.githubusercontent.com/bac75cc94a4f8916fe9d259c435d08fe0efa7d4a6e14feb5d2e5ed7fcde99037/68747470733a2f2f696d342e657a6769662e636f6d2f746d702f657a6769662d342d643661356539613736622e676966)
> 
> As you can see in the above code it doesn't seem to validate the request when I click on "Create"
> 
> I have the below `Create.vue` form:
> 
> ```
> //Create.vue
> <script setup>
> import Modal from "@/Pages/Modal";
> import CreatePipelineForm from "@/Pages/Pipeline/Partials/CreatePipelineForm";
> 
> </script>
> 
> <template>
>     <Modal>
>         <template #title> Create Pipeline </template>
>         <CreatePipelineForm />
>     </Modal>
> </template>
> ```
> 
> Inside this create modal, I have a component called `CreatePipelineForm`:
> 
> ```
> //CreatePipelineForm.vue
> <template>
>     <studio-form-section @submitted="createPipeline">
>         <template #form>
>                 <div class="col-span-6">
>                     <text-input v-model="form.name" label="Name" :error="form.errors.name"></studio-input>
>                 </div>
>         </template>
>         <template #actions>
>             <loading-button :loading="form.processing">
>                 Create
>             </loading-button>
>         </template>
>     </studio-form-section>
> </template>
> <script setup>
> import { useForm } from '@inertiajs/inertia-vue3';
> import StudioFormSection from "@/Studio/FormSection";
> import LoadingButton from "@/Studio/LoadingButton";
> 
> const form = useForm({
>     name: '',
>     output_type: 'text',
>     description: '',
> })
> 
> const createPipeline = () => {
>     form.post(route('pipelines.store'), {
>         errorBag: 'createPipeline',
>         preserveScroll: true,
>     })
> }
> </script>
> ```
> 
> Finally, below is the `store()` method in my controller:
> 
> ```
> public function store(Request $request)
> {
>     \Auth::user()
>         ->currentTeam->pipelines()
>         ->create(
>             $request->validate([
>                 "name" => "required|string|min:3|max:255",
>             ])
>         );
> 
>     return redirect()
>         ->route("pipelines.index")
>         ->with("success", "Pipeline created successfully.");
> }
> ```

I have the same problem. :(

**Comment by lepikhinb** [comment] 2022-07-04 05:35
@cristophergv please confirm you’re using the latest version of the **npm** dependency.

`npm i momentum-modal@latest`

**Comment by cristophergv** [comment] 2022-07-04 06:07
If I have the latest versions, I even downgraded axios. All day I have been dealing with this problem and 20 minutes ago I found something strange. If before <template>......</template> I have <script setup> and here inside I put all the js code </script> the validations do not work and the form is reset every time I save it. If I put everything after <template></template><script> here the same code</script>, but without setup in the opening script tag, nothing works either. But, if I leave the opening <script></script> tag after template and put before the <template ></template> tag <script setup> // and here I put a comment or whatever, as long as it exists something typed,</script> everything works perfectly.

Why?

**Comment by lepikhinb** [comment] 2022-07-04 06:09
That's quite an odd behavior yeah. I would be happy to help you resolve the issue if you find time to set up an example project reproducing it.

**Comment by oliverbj** [comment] 2022-07-08 19:32
It's quite odd. 

When trying to submit, I can see in the network tab that it's actually returning a 302 response on the "store" route:

![image](https://user-images.githubusercontent.com/7851696/178058511-0eb3d019-22fa-44f8-81b8-87024410493f.png)

**Comment by oliverbj** [comment] 2022-07-09 19:45
@lepikhinb I cannot recreate the error I have 100%, however please see this repo: [momentum-modal-test](https://github.com/oliverbj/momentum-modal-test)

If you go to `/event` and click on `Create Event` you will see a simple form located in `/event/create`. If you try to submit this form when blank, no error is shown (even though the network request returns an error).

This is somewhat related to my error - only difference is in my own project, it also closes the modal on submit.

**Comment by oliverbj** [comment] 2022-07-09 19:52
I think I figured out why the modal would redirect to the baseRoute on submit (even though validation fails):

 In my modal (from HeadlessUI):
 
 ```html
 <TransitionRoot appear as="template" :show="show" @after-leave="redirect">
 ```

The `@after-leave="redirect"` is the culprit of the behavior. If I remove that, then the page doesn't redirect back to the `baseRoute` - however, the error message is still not shown.

**Comment by lepikhinb** [comment] 2022-07-09 20:03
The package **has** to use the same axios instance as Inertia in order to modify headers, but your app also has a different version installed.

This worked for me in your example:
`npm i axios@0.21.4`

Check the demo: https://share.cleanshot.com/9swkQm

Also, I would recommend sticking to Headless UI v1.6.4, as the appearance transition was broken in v1.6.5.

**Comment by oliverbj** [comment] 2022-07-09 20:16
Unfortunately it didn't solve the issue for me (in my own project). In my package.json:

```json
"devDependencies": {
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.5.2",
        "@inertiajs/progress": "^0.2.6",
        "axios": "0.21.1",
       //+ the rest
```

Looking at the `inertiajs/inertia.js` package and their `package.json` file:

```json
  "dependencies": {
    "axios": "^0.21.1",
    "deepmerge": "^4.0.0",
    "qs": "^6.9.0"
  },
```

So it seems like I have the same version of `axios`. 

Where can I see if headers are modified correctly?

**Comment by oliverbj** [comment] 2022-07-09 20:21
> The package **has** to use the same axios instance as Inertia in order to modify headers, but your app also has a different version installed.
> 
> This worked for me in your example: `npm i axios@0.21.4`
> 
> Check the demo: https://share.cleanshot.com/9swkQm
> 
> Also, I would recommend sticking to Headless UI v1.6.4, as the appearance transition was broken in v1.6.5.

This fixed the issue! Thanks!

**Closed** 2022-07-09 20:22 UTC

**Comment by nicko170** [comment] 2022-07-28 05:33
This should be a warning in README.md - spent so long screwing around with validation till downgrading versions worked!

Great package @lepikhinb! Thanks

**Comment by kayintveen** [comment] 2022-09-14 18:19
Same here was tryping 0.21.1 but 0.21.4 did the trick. probably due to the same version as used in inertia.

**Comment by itzJustKranker** [comment] 2023-04-02 14:15
Trying to get validation errors to work again after upgrading my application to inertia v1.0. Seems like somehow it could be related to this issue, as everything else works modal-related, except for redirecting back to the modals on form validation errors.

package.json

```json
"@headlessui/vue": "^1.7.12",
"@inertiajs/vue3": "^1.0.2",
"axios": "1.2.0",
"momentum-modal": "^0.2.1",
```
composer.json

```json
"based/momentum-modal": "^0.2.0",
"inertiajs/inertia-laravel": "^0.6.9",
"laravel/framework": "^10.0",
```

I've tried the usual suspects, deleting node_modules, dumping autoload, clearing caches etc.

Anything else I should try, or anything else I should double-check to get form validation working again w/ modals?

**Comment by itzJustKranker** [comment] 2023-04-02 14:33
> I think I figured out why the modal would redirect to the baseRoute on submit (even though validation fails):
> 
> In my modal (from HeadlessUI):
> 
> ```
> <TransitionRoot appear as="template" :show="show" @after-leave="redirect">
> ```
> 
> The `@after-leave="redirect"` is the culprit of the behavior. If I remove that, then the page doesn't redirect back to the `baseRoute` - however, the error message is still not shown.

Interesting, so scrolling up I noticed this reply. And If I remove `@after-leave="redirect"` from my dialog the validation errors show again, however, it has other undesirable side effects. So doesn't seem like the solution.

**Comment by itzJustKranker** [comment] 2023-04-02 16:42
got it working, my issue was with the package.lock.json. Somehow this line got added which must have been why my own package.json w/ 1.2.0 was not working correctly.

```json
"node_modules/@inertiajs/core/node_modules/axios": {
    "version": "1.3.4",
}
```
I see `^1.2.0` in the inertiajs/core [package.json](https://github.com/inertiajs/inertia/blob/master/packages/core/package.json). I wonder if my order of installs was at some point out of whack which let the axios version upgrade to the latest and lock itself...?

Anyway, for anyone else struggling after an upgrade, don't forget to check the `package.lock.json` and wipe accordingly.
